In [1]:
#jupytr notebook example
num1 = 2
num2 = 5
sum = num1 + num2
print(f"The sum of {num1} and {num2} is {sum}")
#print with formatting
print("the sum of {0} and {1} is {2}".format(num1, num2, sum)
      )

The sum of 2 and 5 is 7
the sum of 2 and 5 is 7

In [ ]:
## Machine Learning Example
# Loading Data
# Preprocessing
# Training Model
# Evaluating Model
# making predictions

In [12]:
# import libraries
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [17]:

# load a dataset
iris_data = pd.read_csv('iris.csv')
#iris_data = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
# show the columns in the dataset
print(f"columns in dataset are: {iris_data.columns}")
# check dataset with head method to show first five rows
iris_data.head()

columns in dataset are: Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [20]:
#split dataset into features and labels
x = iris_data.drop(columns=['variety'])
y= iris_data['variety']

# show the features for training the model
print(f"features for training the model are: {x.columns}")
# show the labels for training the model
print(f"labels for training the model are: {y.name}")

features for training the model are: Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width'], dtype='object')
labels for training the model are: variety

In [21]:
#show the actual labels
print(f"actual labels are: {y.unique()}")
#show the first five rows of features
print("first five rows of features:")
x.head()

actual labels are: ['Setosa' 'Versicolor' 'Virginica']
first five rows of features:

   sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [24]:
# create a ml  regression model
model = LogisticRegression()

In [ ]:
#train the model
model.fit(x.values, y)

In [27]:
#predict the labels using the trained model
predictions = model.predict([[4.6, 3.5, 1.5, 0.2]])
print(f"predicted label for input [4.6, 3.5, 1.5, 0.2] is: {predictions[0]}")

print(predictions)

predicted label for input [4.6, 3.5, 1.5, 0.2] is: Setosa
['Setosa']